# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rbf_kernel <- function(X, gamma) {
    .Call(`_RcppKPCA_rbf_kernel`, X, gamma)
}

rbf_kernel_predict <- function(X_new, X_train, gamma) {
    .Call(`_RcppKPCA_rbf_kernel_predict`, X_new, X_train, gamma)
}

center_kernel_matrix <- function(K) {
    .Call(`_RcppKPCA_center_kernel_matrix`, K)
}

kpca_eigen_decomp <- function(Kc, n_components) {
    .Call(`_RcppKPCA_kpca_eigen_decomp`, Kc, n_components)
}

